#!/usr/bin/env bash

paths=(
  ".bashrc"
  ".bundle"
  ".gitattributes"
  ".gitconfig"
  ".gitignore"
  ".inputrc"
  ".node-version"
  ".ruby-version"
  ".tmux.conf"
  ".vimrc"
)
for path in ${paths[@]}; do
  local_path="$PWD/$path"
  home_path="$HOME/$path"

  if ! [[ -f $local_path || -d $local_path ]]; then
    echo "$local_path does not exist"
    continue
  fi

  if [[ -f $home_path || -d $home_path ]]; then
    echo "$home_path already exists"
    continue
  fi

  ln -s $local_path $home_path
  echo "Linked $local_path to $home_path"
done
